baseURL = 'http://localhost:1313/'
title = "吾以往之不谏，知来者之可追"
theme = "reimu"
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'

# 语言配置
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true

[languages.en]
languageName = 'English'
weight = 2

[outputs]
home = ["HTML", "RSS", "JSON"]

# 构建配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true