[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.151.0"
  HUGO_ENV = "production"
  NODE_VERSION = "20"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "production"
